name: Prune Container Images
on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch:

permissions:
  packages: write # to be able to delete images

jobs:
  prune-untagged:
    runs-on: ubuntu-latest
    steps:
      - name: Prune
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          container: beth-leaderboard
          dry-run: false # Dry-run first, then change to `false`
          prune-untagged: true
          keep-younger-than: 1 # day
  prune-old-tagged:
    runs-on: ubuntu-latest
    needs: prune-untagged
    steps:
      - name: Prune PRs
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          container: beth-leaderboard
          dry-run: false # Dry-run first, then change to `false`
          keep-younger-than: 10 # days
          keep-tags: |
            pr-latest
            latest
          prune-tags-regexes: .*
